export const IDA_TYPE = [
  { value: 'C', label: 'AID: 輸入申告（申告納税）' },
  { value: 'F', label: 'AID: 輸入申告（賦課課税）' },
  { value: 'Y', label: 'ASD: 輸入申告（少額関税無税）' },
  { value: 'H', label: 'AHK: 輸入（引取）申告' },
  { value: 'N', label: 'AHK: 特例委託輸入（引取）申告' },
  { value: 'J', label: 'AHT: 輸入（引取・特例）申告' },
  { value: 'P', label: 'AHT: 特例委託輸入（引取・特例）申告' },
  { value: 'S', label: 'AIS: 蔵入承認申請' },
  { value: 'M', label: 'AIS: 移入承認申請' },
  { value: 'A', label: 'AIS: 総保入承認申請' },
  { value: 'G', label: 'AIS: 展示等申告' },
  { value: 'K', label: 'AIW: 蔵出輸入申告（申告納税）' },
  { value: 'D', label: 'AIW: 蔵出輸入申告（賦課納税）' },
  { value: 'U', label: 'AIW: 移出輸入申告（申告納税）' },
  { value: 'L', label: 'AIW: 移出輸入申告（賦課納税）' },
  { value: 'B', label: 'AIW: 総保出輸入申告（申告納税）' },
  { value: 'E', label: 'AIW: 総保出輸入申告（賦課納税）' },
  { value: 'R', label: 'AST: 蔵出輸入（引取・特例）申告' },
];
