// 他法令コード
// no: No.
// name: 内容
// code: コード
// imp: 輸入
// exp: 輸出
// bonded: 保税

export const OL_ = [
  { no: 1, code: 'AC', imp: true, exp: false, bonded: false, name: '農薬取締法' },
  { no: 2, code: 'AD', imp: true, exp: true, bonded: true, name: '覚醒剤取締法' },
  { no: 3, code: 'AM', imp: true, exp: false, bonded: true, name: 'アルコール事業法' },
  { no: 4, code: 'AN', imp: true, exp: true, bonded: true, name: '家畜伝染病予防法' },
  { no: 5, code: 'CA', imp: true, exp: true, bonded: true, name: '大麻取締法' },
  { no: 6, code: 'CP', imp: false, exp: true, bonded: false, name: '文化財保護法' },
  {
    no: 7,
    code: 'CR',
    imp: true,
    exp: false,
    bonded: true,
    name: '化学物質の審査及び製造等の規制に関する法律',
  },
  { no: 8, code: 'EI', imp: false, exp: true, bonded: true, name: '輸出入取引法' },
  { no: 9, code: 'EX', imp: true, exp: false, bonded: true, name: '火薬類取締法' },
  { no: 10, code: 'FD', imp: true, exp: false, bonded: true, name: '食品衛生法' },
  {
    no: 11,
    code: 'FL',
    imp: true,
    exp: false,
    bonded: true,
    name: '肥料の品質の確保等に関する法律',
  },
  {
    no: 12,
    code: 'FM',
    imp: true,
    exp: false,
    bonded: true,
    name: '主要食糧の需給及び価格の安定に関する法律',
  },
  { no: 13, code: 'FO', imp: false, exp: true, bonded: true, name: '林業種苗法' },
  { no: 14, code: 'FR', imp: true, exp: false, bonded: true, name: '水産資源保護法' },
  { no: 15, code: 'FS', imp: true, exp: false, bonded: true, name: '銃砲刀剣類所持等取締法' },
  { no: 16, code: 'GA', imp: true, exp: false, bonded: true, name: '高圧ガス保安法' },
  {
    no: 17,
    code: 'HU',
    imp: true,
    exp: true,
    bonded: true,
    name: '鳥獣の保護及び管理並びに狩猟の適正化に関する法律関係',
  },
  { no: 18, code: 'IA', imp: true, exp: false, bonded: true, name: '外来生物法' },
  { no: 19, code: 'MA', imp: true, exp: false, bonded: true, name: '畜産経営の安定に関する法律' },
  {
    no: 20,
    code: 'MM',
    imp: false,
    exp: true,
    bonded: false,
    name: '道路運送車両法（マニュアル確認）',
  },
  {
    no: 21,
    code: 'MA',
    imp: false,
    exp: true,
    bonded: false,
    name: '道路運送車両法（システム確認）',
  },
  { no: 22, code: 'NA', imp: true, exp: true, bonded: true, name: '麻薬及び向精神薬取締法' },
  { no: 23, code: 'OP', imp: true, exp: true, bonded: true, name: 'あへん法' },
  {
    no: 24,
    code: 'PA',
    imp: true,
    exp: false,
    bonded: true,
    name: '医薬品、医療機器等の品質、有効性及び安全性の確保等に関する法律',
  },
  { no: 25, code: 'PD', imp: true, exp: false, bonded: true, name: '毒物及び劇物取締法' },
  {
    no: 26,
    code: 'PE',
    imp: true,
    exp: false,
    bonded: true,
    name: '石油の備蓄の確保等に関する法律',
  },
  { no: 27, code: 'PL', imp: true, exp: true, bonded: true, name: '植物防疫法' },
  { no: 28, code: 'PM', imp: true, exp: false, bonded: true, name: '感染症予防法' },
  { no: 29, code: 'PS', imp: true, exp: false, bonded: true, name: '郵便切手類模造等取締法' },
  { no: 30, code: 'RA', imp: true, exp: true, bonded: true, name: '狂犬病予防法' },
  { no: 31, code: 'SH', imp: true, exp: false, bonded: true, name: '労働安全衛生法' },
  {
    no: 32,
    code: 'SP',
    imp: true,
    exp: false,
    bonded: true,
    name: '砂糖及びでん粉の価格調整に関する法律',
  },
  { no: 33, code: 'ST', imp: true, exp: false, bonded: true, name: '印紙等模造取締法' },
];
