const t = [
  { no: 1, label: '農薬取締法', value: 'AC' },
  { no: 2, label: '覚醒剤取締法', value: 'AD' },
  { no: 3, label: 'アルコール事業法', value: 'AM' },
  { no: 4, label: '家畜伝染病予防法', value: 'AN' },
  { no: 5, label: '大麻取締法', value: 'CA' },
  { no: 6, label: '文化財保護法', value: 'CP' },
  { no: 7, label: '化学物質の審査及び製造等の規制に関する法律', value: 'CR' },
  { no: 8, label: '輸出入取引法', value: 'EI' },
  { no: 9, label: '火薬類取締法', value: 'EX' },
  { no: 10, label: '食品衛生法', value: 'FD' },
  { no: 11, label: '肥料の品質の確保等に関する法律', value: 'FL' },
  { no: 12, label: '主要食糧の需給及び価格の安定に関する法律', value: 'FM' },
  { no: 13, label: '林業種苗法', value: 'FO' },
  { no: 14, label: '水産資源保護法', value: 'FR' },
  { no: 15, label: '銃砲刀剣類所持等取締法', value: 'FS' },
  { no: 16, label: '高圧ガス保安法', value: 'GA' },
  {
    no: 17,
    label: '鳥獣の保護及び管理並びに狩猟の適正化に関する法律関係',
    value: 'HU',
  },
  { no: 18, label: '外来生物法', value: 'IA' },
  { no: 19, label: '畜産経営の安定に関する法律', value: 'MA' },
  { no: 20, label: '道路運送車両法（マニュアル確認）', value: 'MM' },
  { no: 21, label: '道路運送車両法（システム確認）', value: 'MS' },
  { no: 22, label: '麻薬及び向精神薬取締法', value: 'NA' },
  { no: 23, label: 'あへん法', value: 'OP' },
  {
    no: 24,
    label: '医薬品、医療機器等の品質、有効性及び安全性の確保等に関する法律',
    value: 'PA',
  },
  { no: 25, label: '毒物及び劇物取締法', value: 'PD' },
  { no: 26, label: '石油の備蓄の確保等に関する法律', value: 'PE' },
  { no: 27, label: '植物防疫法', value: 'PL' },
  { no: 28, label: '感染症予防法', value: 'PM' },
  { no: 29, label: '郵便切手類模造等取締法', value: 'PS' },
  { no: 30, label: '狂犬病予防法', value: 'RA' },
  { no: 31, label: '労働安全衛生法', value: 'SH' },
  { no: 32, label: '砂糖及びでん粉の価格調整に関する法律', value: 'SP' },
  { no: 33, label: '印紙等模造取締法', value: 'ST' },
];
