name: CI CD with docker
on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Install packages
      #   run: |
      #     lerna clean -y
      #     lerna bootstrap
      # - name: Run yarn build
      #   run: yarn build:all
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_TOKEN }}
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sk-houtai:latest
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: echo "${{ secrets.AWS_PEM }}" | tr -d '\r' > wxkeypair.pem
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: ssh
        run: ssh -i ${{ secrets.AWS_PEM }} ubuntu@13.112.93.138
        # bash ./docker/deploy.sh
      - name: List files in the repository
        run: ls 