name: CI CD with docker
on: 
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Echo secrets
        env:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo username: "$username" 
          echo password: "$password" 

      - name: Install packages
        run: |
          lerna clean -y
          lerna bootstrap

      - name: Run yarn build
        run: yarn build:all

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image 
        run: |
          docker image build -t ${{ secrets.DOCKERHUB_USERNAME }}/sk-houtai
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sk-houtai