name: CI CD with docker
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request
    steps:
      - run: echo "${GITHUB_REF#refs/heads/}" # PRの番号が取得されてしまいます
      - run: echo "${GITHUB_HEAD_REF}"
      - run: echo "${{ github.ref }}"
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - if: startsWith( github.ref, 'refs/tags/v' )
#         env:
#           REF: ${{ github.ref }}
#         run: echo "${REF##*/}"
#       - uses: actions/checkout@v2
#       - name: Clean packages
#         run: lerna clean -y
#       - name: Install packages
#         run: lerna bootstrap
#       - name: Run yarn build
#         run: yarn build:all
#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_TOKEN }}
#       - name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           context: ./
#           file: ./docker/docker-build
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sk-houtai
#       - name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}

#   deploy:
#     needs: [build]
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: List files in the repository
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.AWS_HOST }}
#           username: ${{ secrets.AWS_USERNAME }}
#           key: ${{ secrets.AWS_PEM }}
#           script: |
#             cd ~
#             bash ./docker/deploy.sh
