name: deploy to s3
on:
  push:
    branches: [ prod ]
    paths: 
        - "packages/e-jp-cn/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean packages
        run: lerna clean -y
      - name: Install packages
        run: lerna bootstrap
      - name: Run yarn build
        run: yarn build @sk-houtai/e-jp-cn
      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: public/

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download build result
        uses: actions/download-artifact@v2
        with:
          name: build
          path: public/
      - name: Publish to AWS S3
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
          FROM_PATH: "public/"
          DEST_PATH: "s3://www.sclogi.jp"