name: deploy to s3 e-jp-cn-prod
on:
  push:
    branches: [ prod ]
    paths:
      - 'apps/expt-jp-cn/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Clean packages
        run: yarn cache clean
      - name: Install packages
        run: yarn
      - name: Run yarn build
        run: yarn workspace @sk-houtai/e-jp-cn build:prod
      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: public/

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download build result
        uses: actions/download-artifact@v3
        with:
          name: build
          path: public/
      - name: Publish to AWS S3
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'
          FROM_PATH: 'public/houtai-export-jp-cn'
          DEST_PATH: 's3://www.sclogi.jp/houtai-export-jp-cn'
          OPTIONS: '--delete'
