name: CI CD with docker
on:
  push:
    branches: [master]
      tags: 
        - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Image digest
        run: echo ${{ github.ref}}
        with:
          tag_name: ${{ github.ref }}